module.exports = {
  successCode: 0,
  successStatus: "success",
  successMessage: "สำเร็จ",

  loginSuccess: "เข้าสู่ระบบสำเร็จ",
  registerSuccess: "สมัครสมาชิกสำเร็จ",
  openServerSuccess: "เปิดเครื่องสำเร็จ",
  shutdownServerSuccess: "ปิดเครื่องสำเร็จ",
  uploadFileSuccess: "อัพโหลดไฟล์สำเร็จ",
  deleteServerSuccess: "ลบเซิร์ฟเวอร์สำเร็จ",
  SubmitDataSuccess: "เพิ่มข้อมูลสำเร็จ",

  errorCode: 1,
  errorStatus: "error",
  errorMessage: "ผิดพลาด",

  errorConnection: "ไม่สามารถเชื่อมต่อระบบได้",
  userNotfound: "ไม่พบสมาชิกในระบบ",
  errorLogin: "อีเมล์หรือรหัสผ่านผิด",
  errorEmpLogin: "ชื่อผู้ใช้งานหรือรหัสผ่านผิด",
  errorInput: "กรอกข้อมูลไม่ครบ",
  errorChangePassword: "รหัสผ่านทั้งสองช่องไม่ตรงกัน",
  errorEmailRegister: "มีอีเมล์นี้แล้วในระบบ",
  errorUsernameRegister: "มี Username นี้แล้วในระบบ",
  errorOpenServer: "เปิดเครื่องไม่สำเร็จ",
  errorShutdownServer: "ปิดเครื่องไม่สำเร็จ",
  erroruploadFile: "อัพโหลดไฟล์ไม่สำเร็จ",
  errorDeleteServer: "ลบเซิร์ฟเวอร์ไม่สำเร็จ",
}